xfsprogs: depends on MMU
Fixes http://sysmic.org/~jezz/results/17f32103:

xfs_fsr.o: In function `fsrallfs':
/home/jezz/br-continuous/cfgs/45-bf609-bfin-uclibc-nommu-ext/build/xfsprogs-3.1.11/fsr/xfs_fsr.c:617: undefined reference to `_fork'
collect2: ld returned 1 exit status

madvise.o: In function `madvise_f':
/home/jezz/br-continuous/cfgs/45-bf609-bfin-uclibc-nommu-ext/build/xfsprogs-3.1.11/io/madvise.c:111: undefined reference to `_madvise'
mincore.o: In function `mincore_f':
/home/jezz/br-continuous/cfgs/45-bf609-bfin-uclibc-nommu-ext/build/xfsprogs-3.1.11/io/mincore.c:77: undefined reference to `_mincore'
collect2: ld returned 1 exit status

[Peter: don't mention mmu dependency in comment]
Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>