vsftpd: Fix dependency for needs mmu
Commit 2eb995759 "vsftpd: needs mmu" adds "depends on BR2_TOOLCHAIN_HAS_THREADS".

The build error is:
sysutil.c:(.text+0x37ac): undefined reference to `fork'

Thus it should depend on BR2_USE_MMU rather than BR2_TOOLCHAIN_HAS_THREADS.

Cc: Gustavo Zacarias <gustavo@zacarias.com.ar>
Signed-off-by: Axel Lin <axel.lin@ingics.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>