iprutils: Fix static build by passing the libraries in the right order
This mistake was causing failures like this one:

m_post.c:(.text+0x60): undefined reference to `wattr_on'

Patch sent upstream:
  https://sourceforge.net/p/iprdd/iprutils/merge-requests/1/

Fixes:
  http://autobuild.buildroot.net/results/500/5004e7b230635e0605acdd17d2b7d2d01fc5075c/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Tested-by: Gustavo Zacarias <gustavo@zacarias.com.ar>
Acked-by: Gustavo Zacarias <gustavo@zacarias.com.ar>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>